repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-docstring-first
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
    -   id: requirements-txt-fixer
-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.32.0
    hooks:
    -   id: yapf
        additional_dependencies:
        - toml
-   repo: https://github.com/PyCQA/prospector
    rev: 1.8.0rc1
    hooks:
    # Includes:
    # pylint
    # pycodestyle
    # pyflakes  (this and pycodestyle == flake8)
    # mccabe
    # pydocstyle
    # mypy
    # bandit
    # vulture
    -   id: prospector
        additional_dependencies:
        - ".[with_mypy,with_bandit,with_vulture]"
-   repo: https://github.com/PyCQA/doc8
    rev: 0.10.1
    hooks:
    -   id: doc8
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
    -   id: pyupgrade
        args: [--py37-plus]
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.7.1
    hooks:
    -   id: reorder-python-imports
        args: [--py37-plus]
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.2.1
    hooks:
    -   id: add-trailing-comma
        args: [--py36-plus]
-   repo: https://github.com/asottile/setup-cfg-fmt
    rev: v1.20.0
    hooks:
    -   id: setup-cfg-fmt
-   repo: local
    hooks:
    -   id: git-diff
        name: git diff
        entry: git diff --exit-code
        language: system
        pass_filenames: false
        always_run: true
